trigger:
- master

stages:
- stage: Acceptation
  jobs:
  - job: AcceptationEnvironment
    continueOnError: false
    steps:
    - task: TerraformInstaller@0
      displayName: install
      inputs:
        terraformVersion: '1.0.9'

    - task: TerraformTaskV2@2
      displayName: init
      inputs:
        provider: 'azurerm'
        command: 'init'
        workingDirectory: 'Terraform/'
        commandOptions: '-reconfigure'
        backendServiceArm: 'azure-spn'
        backendAzureRmResourceGroupName: 'terraform-rg'
        backendAzureRmStorageAccountName: 'adonisterraformstorage'
        backendAzureRmContainerName: 'adonisterraformcontainer'
        backendAzureRmKey: 'terraform.tfstate'
    - task: TerraformTaskV2@2
      displayName: 'validate'
      inputs:
        provider: 'azurerm'
        command: 'validate'
        workingDirectory: 'Terraform/'

    - task: TerraformTaskV2@2
      displayName: 'plan'
      inputs:
        provider: 'azurerm'
        command: 'plan'
        workingDirectory: 'Terraform/'
        environmentServiceNameAzureRM: 'azure-spn'

    - task: TerraformTaskV2@2
      displayName: 'apply'
      inputs:
        provider: 'azurerm'
        command: 'apply'
        workingDirectory: 'Terraform/'
        environmentServiceNameAzureRM: 'azure-spn'

  - stage: desolation
  jobs:
    - job: destruction
      continueOnError: false
      steps:
            - task: TerraformInstaller@0
              displayName: 'install'
              inputs:
                terraformVersion: '0.12.3'
            - task: TerraformTaskV2@2
              displayName: 'init'
              inputs:
                provider: 'azurerm'
                command: 'init'
                workingDirectory: '$(System.DefaultWorkingDirectory)/Terraform'
                backendServiceArm: 'azure-spn'
                backendAzureRmResourceGroupName: 'terraform-rg'
                backendAzureRmStorageAccountName: 'adonisterraformstorage'
                backendAzureRmContainerName: 'adonisterraformcontainer'
                backendAzureRmKey: 'terraform.tfstate'
            - task: TerraformTaskV2@2
              inputs:
                provider: 'azurerm'
                command: 'destroy'
                workingDirectory: '$(System.DefaultWorkingDirectory)/Terraform'
                environmentServiceNameAzureRM: 'azure-spn'