trigger:
- master

stages:
- stage: Acceptation
  jobs:
  - job: AcceptationEnvironment
    continueOnError: false
    steps:
    - task: TerraformInstaller@0
      displayName: install
      inputs:
        terraformVersion: '1.0.9'

    - task: TerraformTaskV2@2
      displayName: init
      inputs:
        provider: 'azurerm'
        command: 'init'
        workingDirectory: 'Terraform/'
        commandOptions: '-reconfigure'
        backendServiceArm: 'azure-spn'
        backendAzureRmResourceGroupName: 'terraform-rg'
        backendAzureRmStorageAccountName: 'adonisterraformstorage'
        backendAzureRmContainerName: 'adonisterraformcontainer'
        backendAzureRmKey: 'terraform.tfstate'
    - task: TerraformTaskV2@2
      displayName: 'validate'
      inputs:
        provider: 'azurerm'
        command: 'validate'
        workingDirectory: 'Terraform/'

    - task: TerraformTaskV2@2
      displayName: 'plan'
      inputs:
        provider: 'azurerm'
        command: 'plan'
        workingDirectory: 'Terraform/'
        commandOptions: '-lock=false'
        environmentServiceNameAzureRM: 'azure-spn'

    - task: TerraformTaskV2@2
      displayName: 'apply'
      inputs:
        provider: 'azurerm'
        command: 'apply'
        workingDirectory: 'Terraform/'
        commandOptions: '-lock=false'
        environmentServiceNameAzureRM: 'azure-spn'

    - task: MavenAuthenticate@0
      inputs:
        artifactsFeeds: 'adonisprovisioning'

    - task: Maven@3
      inputs:
        mavenPomFile: 'pom.xml'
        options: '-Dmaven.test.skip -Dcheckstyle.skip'
        publishJUnitResults: true
        testResultsFiles: '**/surefire-reports/TEST-*.xml'
        javaHomeOption: 'JDKVersion'
        mavenVersionOption: 'Default'
        mavenAuthenticateFeed: false
        effectivePomSkip: false
        sonarQubeRunAnalysis: false

    - task: PublishPipelineArtifact@1
      inputs:
        targetPath: '$(System.DefaultWorkingDirectory)'
        artifact: 'petclinic.jar'
        publishLocation: 'pipeline'

    - task: DownloadPipelineArtifact@2
      inputs:
        buildType: 'current'
        artifactName: 'petclinic.jar'
        itemPattern: '**/**.jar'
        targetPath: '$(Pipeline.Workspace)'

    - task: DockerInstaller@0
      inputs:
        dockerVersion: '17.09.0-ce'

    - task: Docker@2
      inputs:
        containerRegistry: 'Dockerhub'
        repository: 'adonismi/provisioning'
        command: 'buildAndPush'
        Dockerfile: '**/Dockerfile'
        buildContext: '$(Pipeline.Workspace)'
        tags: 'pipeline'
