#For testing specific parts of the first pipeline

stages:
- stage: Testing
  jobs:
  - job: Test1
    continueOnError: false
    steps:


    - task: DownloadSecureFile@1
      inputs:
        secureFile: 'PrivateKey SSH local'

    - task: SSH@0
      inputs:
        sshEndpoint: 'Terraform AzureVM SSH'
        runOptions: 'commands'
        commands: 'pwd'
        readyTimeout: '20000'

    - task: Ansible@0
      inputs:
        ansibleInterface: 'agentMachine'
        playbookPathOnAgentMachine: 'Ansible/provisioning'
        inventoriesAgentMachine: 'noInventory'
