#For testing specific parts of the first pipeline

stages:
- stage: Testing
  jobs:
  - job: Test1
    continueOnError: false
    steps:

    - task: Ansible@0
      inputs:
        ansibleInterface: 'remoteMachine'
        connectionOverSsh: 'Terraform AzureVM SSH'
        playbookSourceRemoteMachine: 'agentMachine'
        playbookRootRemoteMachine: 'Ansible/'
        playbookPathLinkedArtifactOnRemoteMachine: 'Ansible/Playbook1.yml'
        inventoriesRemoteMachine: 'file'
        inventoryFileSourceRemoteMachine: 'agentMachine'
        inventoryFileLinkedArtifactOnRemoteMachine: 'hosts'