#For testing specific parts of the first pipeline

stages:
- stage: Testing
  jobs:
  - job: Test1
    continueOnError: false
    steps:

    - task: CmdLine@2
      inputs:
        script: 'curl 20.73.45.11:8080'
        failOnStderr: false

    - task: SSH@0
      displayName: 'Curl Petclinic'
      inputs:
        sshEndpoint: 'Terraform AzureVM SSH -m PEM'
        runOptions: 'commands'
        commands: 'curl localhost:8080'
        readyTimeout: '20000'