#For testing specific parts of the first pipeline

stages:
- stage: Testing
  jobs:
  - job: Test1
    continueOnError: false
    steps:


    - task: Ansible@0
      inputs:
        ansibleInterface: 'remoteMachine'
        connectionOverSsh: 'Terraform AzureVM SSH -m PEM'
        playbookSourceRemoteMachine: 'agentMachine'
        playbookRootRemoteMachine: 'Ansible/'
        playbookPathLinkedArtifactOnRemoteMachine: 'Playbook1.yml'
        inventoriesRemoteMachine: 'inlineContent'
        inventoryInlineContentRemoteMachine: 'localhost ansible_connection=local'

