#For testing specific parts of the first pipeline

stages:
- stage: Testing
  jobs:
  - job: Test1
    continueOnError: false
    steps:


    - task: DownloadSecureFile@1
      inputs:
        secureFile: 'PrivateKey SSH local'

    - task: Ansible@0
      inputs:
        ansibleInterface: 'agentMachine'
        playbookPathOnAgentMachine: 'Ansible/provisioning'
        inventoriesAgentMachine: 'file'
        inventoryFileOnAgentMachine: 'hosts'
