#For testing specific parts of the first pipeline

stages:
- stage: Testing
  jobs:
  - job: Test1
    continueOnError: false
    steps:
    - task: SSH@0
      inputs:
        sshEndpoint: 'ProductionEnvironment'
        runOptions: 'commands'
        commands: |
          sudo docker container ls
          sudo docker pull adonismi/provisioning:pipeline
          sudo docker stop petclinic
          sudo docker rm petclinic
          sudo docker run -d -p 8080:8080 --name=petclinic adonismi/provisioning:pipeline
        readyTimeout: '20000'
        failOnStdErr: false

    - task: CmdLine@2
      displayName: 'Delay + Curl Petclinic'
      inputs:
        script: |
          ping google.com -c 20
          curl http://40.71.87.48:8080/
          