#For testing specific parts of the first pipeline

stages:
- stage: Testing
  jobs:
  - job: Test1
    continueOnError: false
    steps:

    - task: Ansible@0
      displayName: 'Ansible Playbook'
      inputs:
        ansibleInterface: 'remoteMachine'
        connectionOverSsh: 'Terraform AzureVM SSH -m PEM'
        playbookSourceRemoteMachine: 'agentMachine'
        playbookRootRemoteMachine: 'Ansible/'
        playbookPathLinkedArtifactOnRemoteMachine: 'provisioning'
        inventoriesRemoteMachine: 'inlineContent'
        inventoryInlineContentRemoteMachine: 'localhost ansible_connection=local'
        failOnStdErr: false
    - task: SSH@0
      displayName: 'Docker Pull&Run'
      inputs:
        sshEndpoint: 'Terraform AzureVM SSH -m PEM'
        runOptions: 'commands'
        commands: |
          sudo docker pull adonismi/provisioning:latest
          sudo docker run -d -p 8080:8080 --name=petclinic adonismi/provisioning:pipeline
        readyTimeout: '20000'
