#For testing specific parts of the first pipeline

stages:
- stage: Testing
  jobs:
  - job: Test1
    continueOnError: false
    steps:


    - task: DownloadSecureFile@1
      inputs:
        secureFile: 'PrivateKey SSH local'

    - task: SSH@0
      inputs:
        sshEndpoint: 'Terraform AzureVM SSH'
        runOptions: 'commands'
        commands: |
          sudo yum install epel-release
          sudo yum install ansible
          ansible-playbook -i /home/vsts/work/1/s/hosts /home/vsts/work/1/s/Ansible/Playbook1.yml
        readyTimeout: '20000'

    - task: CmdLine@2
      inputs:
        script: 'cat hosts'

    - task: Ansible@0
      inputs:
        ansibleInterface: 'agentMachine'
        playbookPathOnAgentMachine: 'Ansible/Playbook1.yml'
        inventoriesAgentMachine: 'file'
        inventoryFileOnAgentMachine: 'hosts'
