#For testing specific parts of the first pipeline

stages:
- stage: Testing
  jobs:
  - job: Test1
    continueOnError: false
    steps:
    - task: CmdLine@2
      displayName: 'Curl Petclinic'
      inputs:
        script: 'curl 20.73.45.11:8080'
        failOnStderr: false

  - job: RunsOnServer
    pool: Server
    steps:
    - task: Delay@1
      inputs:
        delayForMinutes: '1' 

  - job: Test1
    continueOnError: false
    steps:
    - task: CmdLine@2
      displayName: 'Curl Petclinic'
      inputs:
        script: 'curl 20.73.45.11:8080'
        failOnStderr: false
